# Generated by Django 5.1.1 on 2024-11-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0012_featureproject_project_alter_donation_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_signup_user',
            field=models.BooleanField(default=False),
        ),
    ]
