# Generated by Django 5.1.1 on 2024-11-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0013_remove_profile_birthday_profile_is_signup_user'),
        ('HomeAPP', '0015_delete_profile'),
    ]

    operations = [
    ]
