# Generated by Django 5.0.6 on 2024-11-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0016_merge_20241123_2101'),
        ('HomeAPP', '0035_alter_profile_user'),
    ]

    operations = [
    ]
